name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.2.0
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface: # ^4.0.0
    git:
      url: https://github.com/t-k-c/flutter_cache_manager.git
      path: cached_network_image_platform_interface
      ref: develop
  flutter:
    sdk: flutter
  flutter_cache_manager: #^3.3.2
    git:
      url: https://github.com/t-k-c/flutter_cache_manager.git
      path: flutter_cache_manager
      ref: develop

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
