name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
version: 3.3.1
environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface: #^4.0.0
    git:
      url: https://github.com/t-k-c/flutter_cache_manager.git
      path: cached_network_image_platform_interface
      ref: develop
  cached_network_image_web: #^1.1.1
    git:
        url: https://github.com/t-k-c/flutter_cache_manager.git
        path: cached_network_image_web
        ref: develop
      
  flutter:
    sdk: flutter
  flutter_cache_manager: #^3.3.2
    git:
      url: https://github.com/t-k-c/flutter_cache_manager.git
      path: flutter_cache_manager
      ref: develop
  octo_image: ^2.0.0

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
